apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server-1
  template:
    metadata:
      labels:
        app: nginx-server-1
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config-1

