apiVersion: v1
kind: Service
metadata:
  name: nginx-server-1
spec:
  selector:
    app: nginx-server-1
  ports:
    - protocol: TCP
      port: {{ .Values.nginxServer.servicePort }}
      targetPort: {{ .Values.nginxServer.servicePort }}
